Repository HIMDanny/kanban-task-manager, pull requests merged in 2023-06, with the labels that each got.

#30 ktm-28: Add nestjs in project
  .gitignore
  backend/.eslintrc.js
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.build.json
  backend/tsconfig.json
Labels: backend

#32 ktm-29: Add prisma in project
  backend/.env.example
  backend/docker-compose.yml
  backend/package-lock.json
  backend/package.json
  backend/prisma/schema.prisma
Labels: backend

#39 ktm-21: Add vite in project
  client/.eslintrc.cjs
  client/.gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/.gitkeep
  client/src/App.tsx
  client/src/assets/.gitkeep
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: good first issue, frontend

#57 ktm-40: Add scaffolding styles
  client/package.json
  client/src/assets/styles/global-style.ts
  client/src/main.tsx
  package-lock.json
Labels: enhancement, frontend

#58 ktm-55: Add board table
  .eslintrc.js
  .ls-lint.yml
  backend/.eslintrc.js
  backend/.prettierignore
  backend/kanban-task-manager.postman_collection.json
  backend/package.json
  backend/prisma/migrations/20230623082534_init/migration.sql
  backend/prisma/migrations/migration_lock.toml
  backend/prisma/schema.prisma
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/src/packages/board/board.controller.ts
  backend/src/packages/board/board.module.ts
  backend/src/packages/board/board.repository.ts
  backend/src/packages/board/board.service.ts
  backend/src/packages/board/libs/dto/board-create-request.dto.ts
  backend/src/packages/board/libs/dto/board-create-response.dto.ts
  backend/src/packages/board/libs/dto/board-delete-response.dto.ts
  backend/src/packages/board/libs/dto/board-get-all-items-response.dto.ts
  backend/src/packages/board/libs/dto/board-get-one-item-request.dto.ts
  backend/src/packages/board/libs/dto/board-get-one-item-response.dto.ts
  backend/src/packages/board/libs/dto/board-update-request.dto.ts
  backend/src/packages/board/libs/dto/board-update-response.dto.ts
  backend/src/packages/board/libs/dto/board.dto.ts
  backend/src/packages/board/libs/dto/dto.ts
  backend/src/packages/board/libs/helpers/maps/map-to-dto.ts
  backend/src/packages/board/libs/helpers/pipes/pipes.ts
  backend/src/packages/board/libs/helpers/pipes/zod-validation.pipe.ts
  backend/src/packages/board/libs/validation-schemas/board-create.validation-schema.ts
  backend/src/packages/board/libs/validation-schemas/board-update.validation-schema.ts
  backend/src/packages/board/libs/validation-schemas/board-validate-parameters.validation-schema.ts
  backend/src/packages/board/libs/validation-schemas/validation-schemas.ts
  backend/src/packages/prisma/prisma.module.ts
  backend/src/packages/prisma/prisma.service.ts
  package-lock.json
Labels: backend

#63 ktm-36: Add colors
  client/src/assets/styles/themes.ts
Labels: enhancement, frontend

#64 ktm-38: Add swagger
  .eslintrc.js
  backend/.eslintrc.js
  backend/nest-cli.json
  backend/package.json
  backend/src/libs/packages/swagger/swagger.ts
  backend/src/main.ts
  package-lock.json
Labels: backend

#69 ktm-37: Add typography
  client/index.html
  client/src/assets/styles/global-style.ts
Labels: enhancement, frontend

#66 ktm-53: Add react-router-dom in project
  client/package.json
  client/src/components/router/router.tsx
  client/src/main.tsx
  client/src/pages/App.tsx
  package-lock.json
Labels: frontend

#70 ktm-35: Add theme configuration
  client/index.html
  client/src/assets/styles/global-style.ts
  client/src/assets/styles/themes.ts
  client/src/main.tsx
  client/src/types/styled.d.ts
  package-lock.json
Labels: enhancement, frontend

#72 ktm-71: Update styled components and fix theme
  client/package.json
  client/src/types/styled.d.ts
  package-lock.json
Labels: frontend

#73 ktm-9: Icon component
  client/.eslintrc.cjs
  client/package.json
  client/src/assets/icons/board.svg
  client/src/assets/icons/cancel.svg
  client/src/assets/icons/check.svg
  client/src/assets/icons/chevron-down.svg
  client/src/assets/icons/eye-slash.svg
  client/src/assets/icons/eye.svg
  client/src/assets/icons/menu.svg
  client/src/assets/icons/moon.svg
  client/src/assets/icons/sun.svg
  client/src/components/Icon.tsx
  client/src/types/icon.ts
  client/src/types/svg.d.ts
  client/vite.config.ts
  package-lock.json
Labels: enhancement, frontend
