Repository HIMDanny/kanban-task-manager, pull requests merged in 2023-07, with the labels that each got.

#78 ktm-65: Fix code linting in ci
  .eslintrc.js
  .github/workflows/lint.yml
  backend/.lintstagedrc.json
  backend/package.json
  client/package.json
  client/src/main.tsx
  package-lock.json
  package.json
Labels: bug

#76 ktm-1: Button Component
  .ls-lint.yml
  client/src/assets/styles/themes.ts
  client/src/components/button/Button.tsx
  client/src/components/button/components/button-wrapper/ButtonWrapper.tsx
  client/src/types/theme.d.ts
Labels: frontend

#79 ktm-61: Add not found case if board is not exist
  backend/src/packages/board/board.service.ts
Labels: backend

#77 ktm-56: Add logger
  backend/src/app.module.ts
  backend/src/main.ts
  backend/src/packages/board/board.module.ts
  backend/src/packages/board/board.service.ts
  package-lock.json
  package.json
Labels: backend

#84 Task/ktm 5 sidebar component
  backend/src/main.ts
  client/package.json
  client/src/api/api-slice.ts
  client/src/assets/icons/logo-icon.svg
  client/src/assets/icons/logo-text.svg
  client/src/assets/styles/global-style.ts
  client/src/assets/styles/themes.ts
  client/src/components/Logo.tsx
  client/src/components/sidebar/Sidebar.tsx
  client/src/components/sidebar/nav/CreateNewBoardButton.tsx
  client/src/components/sidebar/nav/NavItem.tsx
  client/src/components/sidebar/nav/NavList.tsx
  client/src/components/sidebar/nav/styles.ts
  client/src/main.tsx
  client/src/store/store.ts
  client/src/types/board.ts
  client/src/types/theme.d.ts
  package-lock.json
Labels: enhancement, frontend

#89 ktm-87: Add docs for button component
  .ls-lint.yml
  client/.eslintrc.cjs
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package.json
  client/src/stories/Button.stories.ts
  package-lock.json
Labels: documentation, frontend

#92 ktm-75: Add task table
  backend/kanban-task-manager.postman_collection.json
  backend/prisma/migrations/20230714161816_added_task_table/migration.sql
  backend/prisma/schema.prisma
  backend/src/app.module.ts
  backend/src/packages/column/libs/validation-schemas/column-create.validation-schema.ts
  backend/src/packages/column/libs/validation-schemas/column-update.validation-schema.ts
  backend/src/packages/column/libs/validation-schemas/validation-schemas.ts
  backend/src/packages/task/libs/dto/dto.ts
  backend/src/packages/task/libs/dto/task-create-request.dto.ts
  backend/src/packages/task/libs/dto/task-create-response.dto.ts
  backend/src/packages/task/libs/dto/task-delete-response.dto.ts
  backend/src/packages/task/libs/dto/task-get-all-items-response.dto.ts
  backend/src/packages/task/libs/dto/task-get-one-item-request.dto.ts
  backend/src/packages/task/libs/dto/task-get-one-item-response.dto.ts
  backend/src/packages/task/libs/dto/task-update-request.dto.ts
  backend/src/packages/task/libs/dto/task-update-response.dto.ts
  backend/src/packages/task/libs/dto/task.dto.ts
  backend/src/packages/task/libs/validation-schemas/task-create.validation-schema.ts
  backend/src/packages/task/libs/validation-schemas/task-update.validation-schema.ts
  backend/src/packages/task/libs/validation-schemas/task-validate-parameters.validation-schema.ts
  backend/src/packages/task/libs/validation-schemas/validation-schemas.ts
  backend/src/packages/task/task.controller.ts
  backend/src/packages/task/task.module.ts
  backend/src/packages/task/task.repository.ts
  backend/src/packages/task/task.service.ts
Labels: backend
